### ISSUE TITLE
Conflict with abstracts?

### ISSUE THREAD

**Issue by theufman** [schlcht/microtype#4] opened 2021-12-06 13:41 UTC
I am getting an error when compiling an abstract. When I run the following MWE:

`\documentclass{article}
\usepackage{microtype}

\begin{document}

\begin{abstract}
Test
\end{abstract}
\end{document}`

I get the following error:

`This is pdfTeX, Version 3.141592653-2.6-1.40.23 (MiKTeX 21.10)
entering extended mode
(test_abstract.tex
LaTeX2e <2021-11-15>
L3 programming layer <2021-11-22>
(C:\Users\m\AppData\Local\Programs\MiKTeX\tex/latex/base\article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(C:\Users\m\AppData\Local\Programs\MiKTeX\tex/latex/base\size10.clo))
(C:\Users\m\AppData\Local\Programs\MiKTeX\tex/latex/microtype\microtype.sty
(C:\Users\m\AppData\Local\Programs\MiKTeX\tex/latex/graphics\keyval.sty)
(C:\Users\m\AppData\Local\Programs\MiKTeX\tex/latex/etoolbox\etoolbox.sty)
(C:\Users\m\AppData\Local\Programs\MiKTeX\tex/latex/microtype\microtype-pdftex.
def)
(C:\Users\m\AppData\Local\Programs\MiKTeX\tex/latex/microtype\microtype.cfg))
(C:\Users\m\AppData\Local\Programs\MiKTeX\tex/latex/l3backend\l3backend-pdftex.
def) (test_abstract.aux)
(C:\Users\m\AppData\Local\Programs\MiKTeX\tex/latex/microtype\mt-cmr.cfg)
! Undefined control sequence.
<argument> \z
              @
l.7 \begin{abstract}`

If I run it through, I get the result in the picture attached.

![image](https://user-images.githubusercontent.com/95629835/144856104-6b02c5a8-c668-4b6f-968d-a34edf423086.png)

**Comment by gusbrs** [comment] 2021-12-06 16:25
I'm also affected by this issue (I was coming to report, and found this one already open).

As far as I've experimented, the issue is related to the `item` patch. A temporary workaround is to use `\microtypesetup{nopatch=item}`.

**Comment by theufman** [comment] 2021-12-06 16:44
> I'm also affected by this issue (I was coming to report, and found this one already open).
> 
> As far as I've experimented, the issue is related to the `item` patch. A temporary workaround is to use `\microtypesetup{nopatch=item}`.

This worked for me too. This workaround will hopefully hold until a more permanent solution is found.

**Comment by schlcht** [comment] 2021-12-06 17:06
Thanks, this is effectively the same problem as in #3, and the fix there will also fix this issue, so I'm marking it as a duplicate.

**Closed** 2021-12-10 17:28 UTC
Labels: duplicate
