### ISSUE TITLE
Package microtype Warning: Unable to apply patch 'eqnum' and 'footnote'

### ISSUE THREAD

**Issue by manascimento** [schlcht/microtype#23] opened 2022-09-22 20:33 UTC
When I am using `\RequirePackage{microtype}` on @overleaf with **TeX Live version 2021 and XeLateX**, I get no warnings.

But, If I change the **TeX Live version to 2022** I get the following warnings:

```
Package microtype Warning: Unable to apply patch 'eqnum'
Package microtype Warning: Unable to apply patch 'footnote'
```

<img width="371" alt="image" src="https://user-images.githubusercontent.com/23437243/191844308-047f7748-65df-46ea-860a-371e67a0f31d.png">

If I back to 2021, I have no more warnings again.

I have found a workaround. If I put `\RequirePackage[nopatch={eqnum,footnote}]{microtype}`, the warnings will disappear, but I guess that this solution is not the best way, because in the previous version was working fine.

I found a question similar to mine, but with no answer: https://tex.stackexchange.com/questions/654914/how-to-resolve-this-message-package-microtype-warning-unable-to-apply-patch-e

**Comment by dmackinnon1** [comment] 2022-09-26 18:28
@manascimento - could you provide a minimal example that reproduces this problem with the Overleaf TL 2022 image? If you send this to Overleaf support (support@overleaf.com) that would be helpful.

If you add the latest microtype.sty file to your Overleaf project, does that resolve the issue? Overleaf's current version of microtype is `microtype 2022/03/14 v3.0d` which is slightly behind the latest version.

**Comment by schlcht** [comment] 2022-09-27 21:58
I suspect these warnings were due to the fact that Overleaf had an outdated version of microtype. In view of your report (and other similar questions), I've asked the good people there to update to the current version, which they've thankfully agreed to and which hopefully should resolve the issue for you and everybody else using Overleaf. Therefore I'm closing this as a duplicate. Should you still get warnings, please provide a minimal example.

**Closed** 2022-09-27 21:58 UTC

**Comment by manascimento** [comment] 2022-09-27 22:06
@dmackinnon1 and @schlcht thanks so much for your answers. I just sent an e-mail to @overleaf team as @dmackinnon1 suggested. I'm waiting for the answer from them.

As soon, they replied, I will do another test. If OK, I will update you. If not, I bring more details about the issue.

But, I agree with you that the problem could the version is outdate.

**Comment by manascimento** [comment] 2022-09-28 22:22
Hi everybody!

The @overleaf team helped me to fix this issue.

The order that I was loading some packages raised the warning. Three packages were involved: microtype, hyperref and setspace.

Solution:

`\usepackage{microtype}` should be the first package to be loaded. And `\usepackage{setspace}` must be before `\usepackage{hyperref}`.

So, changing the order to:
```
\usepackage{microtype}
\usepackage{setspace}
\usepackage{hyperref}
```

The warning disappeared.

The reasons you can find here: https://tex.stackexchange.com/questions/188273/using-setspace-package-breaks-footnotes-link.

Thank you, Dan (@overleaf support team) for your attention.

**Comment by schlcht** [comment] 2022-09-29 14:48
Great to hear that your problem is solved now. Just for the record, the order issue only involves setspace and hyperref, whereas microtype may be loaded at any time (before, between or after the two packages). Also just for information, Overleaf now provides the latest version of microtype (thanks, @overleaf!).
